jobs:
  - job: build
    displayName: rclone_ignore
    variables:
      TOOLCHAIN: stable
    pool:
      vmImage: windows-latest
    steps:
      - template: ci/azure-install-rust.yml
      - powershell: cargo build --features tray --release --verbose
        displayName: build rclone_ignore
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'target\release\rclone_ignore.exe'
          ArtifactName: 'rclone_ignore'
          publishLocation: 'container'
        displayName: Publish rclone_ignore
      - task: GithubRelease@0
        displayName: 'Create GitHub Release'
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
        inputs:
          gitHubConnection: github
          repositoryName: dixn/rclone_ignore
          assets: $(Build.ArtifactStagingDirectory)/*.exe