[package]
name = "ws_server"
version = "0.1.0"
authors = ["Michael Kaltschmid <kaltschmidmichael@gmail.com>"]
edition = "2018"

[dependencies]
ws = "0.9.0"
env_logger = "0.6.2"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
lazy_static = "1.3.0"
log = "0.4.8"
